# Configuration des variables pour l'envoi des emails.

# MAIL_USER : nom de l'adresse mail qui va envoyer les emails.
# MAIL_RECIPIENT : nom de l'adresse mail qui va recevoir les emails.
# MAIL_PASS : mot de passe de l'adresse mail du MAIL_USER
# SMTP_SERVER : adresse internet du serveur SMTP de l'adresse mail du MAIL_USER
# SMTP_PORT : port du serveur SMTP de l'adresse mail du MAIL_USER
MAIL_USER: "ow-rpi@gmx.fr"
MAIL_RECIPIENT: "archein.lol@gmail.com"
MAIL_PASS: ""
SMTP_SERVER: "mail.gmx.com"
SMTP_PORT: 587
